### ISSUE TITLE
Thumbnails for Convos

### ISSUE THREAD

**Issue by rnmp** [rnmp/convos#3]
Reference (current gem used for thumbnails): 
https://github.com/rlarcombe/grabbit

**Comment by rnmp** [comment]
from sebastian's progress:

https://github.com/thoughtbot/paperclip/wiki/Attachment-downloaded-from-a-URL
https://github.com/thoughtbot/paperclip/wiki/Quick-Start
https://devcenter.heroku.com/articles/paperclip-s3

> so thumbnail_remote_url should == scrape.images.first ?
> i dont know how to put all this together

**Comment by rnmp** [comment]
@sebastian-dh I've updated the title

**Comment by sebastian-dh** [comment]
No longer needed as of now. One for the future?
