### ISSUE TITLE
vanity urls for convos and topics

### ISSUE THREAD

**Issue by rnmp** [rnmp/convos#4]
for convos:

```
/c/:id/:slug
```

`:slug` by default should be generated from convos' title. e.g. `this-is-your-mom` but it can be replaced with anything to allow for click baits and what not. e.g. `this-is-your-mom-naked`

for topics:

```
/t/:slug
```

`:slug` should be identical to topic's name. perhaps we should prevent topics from having the same name (i don't think this is true in database so please check.) e.g. topic `#random` should be `/t/random`

**Comment by sebastian-dh** [comment]
I propose a url format similar to what reddit currently uses:

/t/topic:slug/c/id/convo:slug

e.g.:
https://www.reddit.com/r/news/comments/3sdzf5/egypt_to_ben_carson_no_the_pyramids_were_not_for/
