### ISSUE TITLE
Fix voting: undo votes, change votes

### ISSUE THREAD

**Issue by sebastian-dh** [rnmp/convos#5]
Overview: https://www.reddit.com/r/learnprogramming/comments/zzbpz/how_and_in_what_language_are_reddits_upvote_and/c698w1c
- Implement back end unvote/change vote functionality
- Fix item_points display: currently changing an upvote to a downvote or vice-versa will change the points counter by an increment of 1, when reversing a vote should change this by 2.

**Comment by rnmp** [comment]
the referenced commit here is actually wrong, i didn't really build this functionally rather fix a related bug
